#!/bin/bash

set -e

VERSION=0.1.0
URL="https://github.com/tomasbasham/dotfiles/archive/v${VERSION}.tar.gz"

download() {
  local scratch="$(mktemp -d "${TMPDIR:-/tmp}/dotfiles.XXXXXXXXX")"
  local archive="${scratch}/dotfiles-${VERSION}"

  echo "downloading dotfiles archive: ${URL}"
  curl -sSL "${URL}" | tar -C "${scratch}" -xzf -

  echo "running install script from: ${archive}"
  "${archive}/scripts/install" "$@"
}

download "$@"
